version: "3"
services:
  mysql:
    image: mysql:8.0.3
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: vim
      MYSQL_DATABASE: vim
      MYSQL_USER: vim
      MYSQL_PASSWORD: vim
